from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_openai import ChatOpenAI
from typing import List, Optional
from datetime import date
import os
import logging

logger = logging.getLogger(__name__)
from utils.custom_prompts import prompt_templates, prompt_template_general
from utils.scenario import Scenario_qa
from utils.check_relevance import check_relevance
from utils.util import count_tokens
from langchain_google_genai import ChatGoogleGenerativeAI
from retrievers.draft_retriever import DraftRetriever
from retrievers.judgement_retriever import JudgementRetriever
from retrievers.newacts_retriever import NewactsRetriever
from retrievers.legislation_retriever import LegislationRetriever
def generate_response(query: str, chat_history: Optional[List[HumanMessage]] = None, task: str = "Other") -> AIMessage:
    # Handle Customization task using Sonar-Pro (Perplexity)
    # Get today's date
    today = date.today()
    logger.debug("Current date: %s", today)
    if task == "Other":
        logger.info("Inside Others task, using web search")
        res = Scenario_qa(query,chat_history)

        return AIMessage(content=res.candidates[0].content.parts[0].text, metadata={"source": {'title':'Disclaimer','content':["This response is generated by AI based on Legal Intelligence"],'docLink':None}},tokens_consumed=res.usage_metadata.total_token_count)
    
    if task == "Legal_Concepts":
        logger.info("Inside Legal Concepts task")
        general_llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite", temperature=0.3)
        # prompt = ChatPromptTemplate.from_template(prompt_template_general)
        prompt = ChatPromptTemplate.from_messages([
            ("user", prompt_template_general),
            MessagesPlaceholder(variable_name="chat_history", optional=True),
            ("user", "Use if required Current Date is:\n{date}"),
            ("user", "{query}"),
        ])

        chain = prompt | general_llm
        response = chain.invoke({'query':query,'chat_history': chat_history,'date':today})
        logger.debug("Legal Concepts response: %s", response.content)
        tokens_used = (
        	response.usage_metadata.get("total_tokens", 0)
        	if getattr(response, "usage_metadata", None)
        		else 0
    	)
        return AIMessage(content=response.content, metadata={"source": {'title':'Disclaimer','content':["This is a AI generated response based on Legal Intelligence"],'docLink':None}}, tokens_consumed=tokens_used)

    # prompt = ChatPromptTemplate.from_messages([
    #     ("system", prompt_templates.get(task, "You are an AI assistant providing legal information.")),
    #     MessagesPlaceholder(variable_name="chat_history", optional=True),
    #     ("user", "Document information:\n{docs}."),
    #     ("user", "Use if required Current Date is:\n{date}"),
    #     ("user", "{query}"),
    # ])
    prompt = ChatPromptTemplate.from_messages([
        # System instructions (your drafting rules)
        ("system", prompt_templates.get(task, "You are an AI assistant providing legal information.")),

        # Past conversation, optional
        MessagesPlaceholder(variable_name="chat_history", optional=True),

        # Retrieved template
        ("user", "Original Draft Template or Newacts or Legislation or Judgment:\n{docs}"),

        # Date if needed
        ("user", "Current Date:\n{date}"),

        # Latest user scenario (most important)
        ("user", "User Query:\n{query}")
    ])

    if task == "Scenario":
        logger.info("Scenario task, using web search")
        res = Scenario_qa(query,chat_history)
        # res_source = res.additional_kwargs["citations"]
        # res_token_count = res.usage_metadata["total_tokens"]
        return AIMessage(content=res.candidates[0].content.parts[0].text, metadata={"source": {'title':'Disclaimer','content':["This response is generated by AI based on Legal Intelligence"],'docLink':None}},tokens_consumed=res.usage_metadata.total_token_count)
    elif task == "Drafting":
        retriever = DraftRetriever()
        docs = retriever.retrieve_documents(query=query)
        documents = docs
    elif task == "Legislation":
        retriever = LegislationRetriever()
        docs = retriever.retrieve_documents(query=query)
        documents = docs
    elif task == "Judgment":
        retriever = JudgementRetriever()
        docs = retriever.retrieve_documents(query=query)
        documents = docs
    elif task == "Newacts":
        retriever = NewactsRetriever()
        docs = retriever.retrieve_documents(query=query)
        documents = docs
    else:
        logger.warning("Unknown task '%s', falling back to web search", task)
        documents = []
    
    if len(documents) == 0:
        res = Scenario_qa(query,chat_history)

        return AIMessage(content=res.candidates[0].content.parts[0].text, metadata={"source": {'title':'Disclaimer','content':["This response is generated by AI based on Legal Intelligence"],'docLink':None}},tokens_consumed=res.usage_metadata.total_token_count)
    

    result = check_relevance(query, documents,task=task)

    if result.isrelevant == 'No':
        logger.info("No relevant document found for this query, falling back to web search")
        res = Scenario_qa(query,chat_history)

        return AIMessage(content=res.candidates[0].content.parts[0].text, metadata={"source": {'title':'Disclaimer','content':["This response is generated by AI based on Legal Intelligence"],'docLink':None}},tokens_consumed=res.usage_metadata.total_token_count)
    logger.info("Final retrieved chunks: %d", len(documents))

    text_source = {
        'title': None,
        'content': [],
        'docLink': None,
        'fileName': None
    }
    for doc in documents:
        source_file = doc.metadata.get('source', 'unknown')
        logger.debug("Original source: %s", source_file)

        # Process source ensuring it's a string
        if isinstance(source_file, dict):
            # If it's a dict, convert it to string representation or get 'source' key if available
            source = source_file.get("source", str(source_file))
        else:
            source = str(source_file)

        # Get the base filename
        source = os.path.basename(source)
        source = os.path.splitext(source)[0]
        logger.debug("Source after processing: %s", source)

        # Get source_name if available, else fallback to processed source
        source_name = doc.metadata.get('source_name', source)
        logger.debug("Source name: %s", source_name)

        # Set title once using source_name
        if text_source['title'] is None:
            text_source['title'] = source_name
            if isinstance(source_file, dict):
                text_source['fileName'] = source_file.get("source", "")
            else:
                text_source['fileName'] = source_file
        # Append content
        text_source['content'].append(doc.page_content)

    
    if task == "Judgment":
        logger.info("Creating PDF link for title=%s, fileName=%s", text_source['title'], text_source['fileName'])

        bucket_name = "lawttorney"
        region_name = "ap-south-1"

        # Ensure 'court' exists and handle casing safely
        s3_root_folder = (documents[0].metadata.get('court') or "").strip()
        s3_root_folder = s3_root_folder.lower()  # normalize casing

        # Normalize path for Linux/Windows
        file_path = text_source['fileName'].replace("\\", "/")
        file = os.path.basename(file_path)
        logger.debug("file: %s", file)

        # Generate the correct S3 key
        if s3_root_folder == "supreme":
            s3_key = f"{s3_root_folder}/{text_source['title']}.pdf"
        elif s3_root_folder == "tribunal":
            s3_key = f"{s3_root_folder}/{file}"
        else:
            logger.debug("Using default S3 key pattern")
            s3_key = f"{s3_root_folder}/{file}"

        # Build the S3 public link
        link = f"https://{bucket_name}.s3.{region_name}.amazonaws.com/{s3_key}"

        # Attach link to the document info
        text_source['docLink'] = link

        logger.debug("s3_root_folder=%s, s3_key=%s", s3_root_folder, s3_key)
        logger.info("Final S3 Link: %s", link)

    docs = "\n\n".join([d.page_content for d in documents])
    source = documents[0].metadata.get('source', 'unknown')

    if task == "Drafting":
        llm = ChatOpenAI(model="gpt-4o", temperature=0.5)
    else:
        # llm = ChatOpenAI(model="gpt-4o", temperature=0.1)
        llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite", temperature=0.1)
    chain = prompt | llm

    response = chain.invoke({"query": query, 'docs': docs, 'chat_history': chat_history,'date':today})
    logger.debug("Generated response for query '%s': %s", query, response)

    # Calculate token count for the generated response
    total_tokens = 0
    if hasattr(response, "response_metadata") and "token_usage" in response.response_metadata:
        total_tokens = response.response_metadata["token_usage"].get("total_tokens", 0)
    elif hasattr(response, "usage_metadata") and "total_tokens" in response.usage_metadata:
        total_tokens = response.usage_metadata["total_tokens"]
    else:
        # Fallback: estimate tokens using your count_tokens function
        total_tokens = count_tokens(response.content)

    return AIMessage(content=response.content, metadata={"source": text_source, 'docLink':None}, tokens_consumed=total_tokens)
