"""Unit tests for core.url_filter.

Covers the three surfaces the module scrubs:
  1. `is_whitelisted_url` — host whitelist decisions
  2. `sanitize_source_records` — API `source_metadata` payload sanitiser
  3. `sanitize_prose` — final_response prose stripper
  4. `StreamingUrlFilter` — rolling-buffer SSE token scrubber

Whitelist policy: URLs on `lawttorney.s3.*.amazonaws.com` (HC judgment PDFs)
and `api.sci.gov.in` (SCI PDFs) are kept. Every other URL is stripped
(Google Search grounding citations, tier-3 web_search_fallback URLs,
authoritative-domain URLs like indiankanoon.org, government portals, etc.).
"""
from __future__ import annotations

import pytest

from core.url_filter import (
    StreamingUrlFilter,
    is_whitelisted_url,
    sanitize_prose,
    sanitize_source_records,
)


# ---------------------------------------------------------------------------
# is_whitelisted_url
# ---------------------------------------------------------------------------

class TestIsWhitelistedUrl:
    def test_none_and_empty(self):
        assert is_whitelisted_url(None) is False
        assert is_whitelisted_url("") is False
        assert is_whitelisted_url("   ") is False

    def test_lawttorney_s3_ap_south_1(self):
        assert is_whitelisted_url(
            "https://lawttorney.s3.ap-south-1.amazonaws.com/bombay high court/xyz.pdf"
        ) is True

    def test_lawttorney_s3_other_region(self):
        assert is_whitelisted_url(
            "https://lawttorney.s3.us-east-1.amazonaws.com/supreme/case.pdf"
        ) is True

    def test_sci_api(self):
        assert is_whitelisted_url(
            "https://api.sci.gov.in/supremecourt/2017/39058/xyz.pdf"
        ) is True

    def test_case_insensitive(self):
        assert is_whitelisted_url(
            "HTTPS://LAWTTORNEY.S3.AP-SOUTH-1.AMAZONAWS.COM/xyz.pdf"
        ) is True

    def test_external_hosts_rejected(self):
        assert is_whitelisted_url("https://indiankanoon.org/doc/12345/") is False
        assert is_whitelisted_url("https://barandbench.com/news/xyz") is False
        assert is_whitelisted_url("https://vakilsearch.com/blog") is False
        assert is_whitelisted_url("https://google.com") is False
        assert is_whitelisted_url("https://legislative.gov.in") is False

    def test_lookalike_hosts_rejected(self):
        # Prefix-match must be strict — a subdomain that only *contains*
        # "lawttorney" but doesn't start with it should be rejected.
        assert is_whitelisted_url("https://evil.com/lawttorney.s3.amazonaws.com/x") is False
        assert is_whitelisted_url("https://api.sci.gov.in.evil.com/xyz") is False
        assert is_whitelisted_url("https://not-api.sci.gov.in/xyz") is False

    def test_http_vs_https(self):
        # Both schemes on whitelisted hosts should be accepted (defensive —
        # nothing in our pipeline emits plain http today, but be safe).
        assert is_whitelisted_url("http://api.sci.gov.in/x") is True
        assert is_whitelisted_url("http://lawttorney.s3.ap-south-1.amazonaws.com/x") is True


# ---------------------------------------------------------------------------
# sanitize_source_records
# ---------------------------------------------------------------------------

class TestSanitizeSourceRecords:
    """Post-2026-08-22 policy: keep ONLY records with a whitelisted PDF URL."""

    def test_none_and_empty(self):
        assert sanitize_source_records(None) == []
        assert sanitize_source_records([]) == []

    def test_scenario_web_record_dropped(self):
        records = [{
            "source_type": "scenario",
            "title": "Some blog post",
            "web_url": "https://indiankanoon.org/doc/12345/",
            "web_title": "Some blog post",
            "agent_name": "Scenario",
        }]
        assert sanitize_source_records(records) == []

    def test_tier3_web_fallback_record_dropped(self):
        records = [{
            "source_type": "newacts",
            "title": "External blog on BNS §115",
            "web_url": "https://vakilsearch.com/blog/bns-115",
            "agent_name": "Newacts",
        }]
        assert sanitize_source_records(records) == []

    def test_ungrounded_ai_marker_dropped(self):
        # web_search_fallback's "no grounding" marker record — no URL, no PDF.
        # Under the new policy, no whitelisted URL means dropped.
        records = [{
            "source_type": "legal_concepts",
            "title": "AI-Generated Legal_Concepts Analysis",
            "content": ["Response generated by AI with web search grounding"],
            "agent_name": "Legal_Concepts",
        }]
        assert sanitize_source_records(records) == []

    def test_legislation_record_no_url_dropped(self):
        # Legislation records carry no URL field — dropped under new policy.
        records = [{
            "source_type": "legislation",
            "title": "Section 302 IPC",
            "content": ["Whoever commits murder..."],
            "section_number": "302",
            "act_name": "Indian Penal Code",
        }]
        assert sanitize_source_records(records) == []

    def test_document_agent_record_dropped(self):
        # PDF-chat agent records carry file_name, no URL — dropped.
        records = [{
            "source_type": "document",
            "title": "uploaded_contract.pdf",
            "file_name": "uploaded_contract.pdf",
            "content": ["Some extracted text..."],
        }]
        assert sanitize_source_records(records) == []

    def test_hc_judgment_record_kept(self):
        s3_url = "https://lawttorney.s3.ap-south-1.amazonaws.com/bombay high court/xyz.pdf"
        records = [{
            "source_type": "judgment",
            "title": "Some HC case",
            "doc_link": s3_url,
            "web_url": s3_url,
            "agent_name": "Judgment",
        }]
        cleaned = sanitize_source_records(records)
        assert len(cleaned) == 1
        assert cleaned[0]["doc_link"] == s3_url
        assert cleaned[0]["web_url"] == s3_url

    def test_sci_pdf_links_filtered(self):
        # Mixed pdf_links list: whitelisted entry survives, blog entry drops,
        # record kept because a whitelisted PDF remains.
        records = [{
            "source_type": "sci_judgment",
            "title": "Some SCI case",
            "pdf_links": [
                {"label": "SCI Judgment", "url": "https://api.sci.gov.in/supremecourt/x.pdf"},
                {"label": "Blog", "url": "https://barandbench.com/xyz"},
            ],
            "agent_name": "SCI_Judgment",
        }]
        cleaned = sanitize_source_records(records)
        assert len(cleaned) == 1
        assert len(cleaned[0]["pdf_links"]) == 1
        assert cleaned[0]["pdf_links"][0]["url"].startswith("https://api.sci.gov.in/")

    def test_record_with_external_web_url_but_valid_pdf_links_kept(self):
        # Kept because of whitelisted pdf_links entry; external web_url nulled.
        records = [{
            "source_type": "sci_judgment",
            "title": "Some case",
            "web_url": "https://external.com/x",
            "web_title": "External source",
            "pdf_links": [
                {"label": "SCI PDF", "url": "https://api.sci.gov.in/x.pdf"},
            ],
        }]
        cleaned = sanitize_source_records(records)
        assert len(cleaned) == 1
        assert cleaned[0]["web_url"] is None
        assert cleaned[0]["web_title"] is None
        assert cleaned[0]["pdf_links"][0]["url"].startswith("https://api.sci.gov.in/")

    def test_mixed_batch(self):
        s3_url = "https://lawttorney.s3.ap-south-1.amazonaws.com/hc/x.pdf"
        sci_url = "https://api.sci.gov.in/y.pdf"
        records = [
            {"source_type": "legislation", "title": "Section 302 IPC"},          # drop (no URL)
            {"source_type": "scenario", "web_url": "https://external.com/x"},    # drop
            {"source_type": "judgment", "doc_link": s3_url},                     # keep
            {"source_type": "newacts", "web_url": "https://vakilsearch.com/x"},  # drop
            {"source_type": "sci_judgment", "pdf_links": [{"url": sci_url}]},    # keep
            {"source_type": "document", "title": "upload.pdf"},                  # drop
        ]
        cleaned = sanitize_source_records(records)
        assert len(cleaned) == 2
        assert cleaned[0]["doc_link"] == s3_url
        assert cleaned[1]["pdf_links"][0]["url"] == sci_url

    def test_non_dict_entries_dropped(self):
        records = ["not a dict", {"source_type": "judgment",
                                  "doc_link": "https://lawttorney.s3.ap-south-1.amazonaws.com/x.pdf"}]
        cleaned = sanitize_source_records(records)
        assert len(cleaned) == 1
        assert cleaned[0]["source_type"] == "judgment"


# ---------------------------------------------------------------------------
# sanitize_prose
# ---------------------------------------------------------------------------

class TestSanitizeProse:
    def test_none_and_empty(self):
        assert sanitize_prose(None) == ""
        assert sanitize_prose("") == ""
        assert sanitize_prose("no urls here") == "no urls here"

    def test_bare_external_url_stripped(self):
        text = "See https://indiankanoon.org/doc/123 for details."
        out = sanitize_prose(text)
        assert "indiankanoon.org" not in out
        # "See :" wrapper should also go
        assert "See" not in out or "See" in out and "https" not in out

    def test_bare_sci_url_kept(self):
        text = "Refer to https://api.sci.gov.in/xyz.pdf for the judgment."
        out = sanitize_prose(text)
        assert "https://api.sci.gov.in/xyz.pdf" in out

    def test_bare_s3_url_kept(self):
        text = "PDF at https://lawttorney.s3.ap-south-1.amazonaws.com/x.pdf here."
        out = sanitize_prose(text)
        assert "lawttorney.s3.ap-south-1.amazonaws.com" in out

    def test_markdown_link_external_dropped_label_kept(self):
        text = "Read [my blog](https://ipleaders.in/xyz) for context."
        out = sanitize_prose(text)
        assert "ipleaders.in" not in out
        assert "my blog" in out  # label preserved

    def test_markdown_link_whitelisted_kept(self):
        text = "See [Judgment PDF](https://api.sci.gov.in/x.pdf)."
        out = sanitize_prose(text)
        assert "https://api.sci.gov.in/x.pdf" in out
        assert "[Judgment PDF]" in out

    def test_source_wrapper_stripped(self):
        text = "The court held X. Source: https://barandbench.com/news/xyz. Then Y."
        out = sanitize_prose(text)
        assert "barandbench.com" not in out
        assert "Source:" not in out
        assert "The court held X." in out
        assert "Then Y." in out

    def test_pdf_links_block_survives(self):
        text = (
            "**PDF Links:**\n"
            "- *Case A*: https://api.sci.gov.in/x.pdf\n"
            "- *Case B*: https://lawttorney.s3.ap-south-1.amazonaws.com/hc/y.pdf\n"
        )
        out = sanitize_prose(text)
        assert "**PDF Links:**" in out
        assert "https://api.sci.gov.in/x.pdf" in out
        assert "lawttorney.s3.ap-south-1.amazonaws.com" in out

    def test_mixed_pdf_links_external_dropped(self):
        text = (
            "**PDF Links:**\n"
            "- *SCI Case*: https://api.sci.gov.in/x.pdf\n"
            "- *Blog analysis*: https://livelaw.in/xyz\n"
        )
        out = sanitize_prose(text)
        assert "https://api.sci.gov.in/x.pdf" in out
        assert "livelaw.in" not in out

    def test_multiple_urls_mixed(self):
        text = (
            "Judgment: https://api.sci.gov.in/x.pdf and See https://google.com/y and "
            "[click](https://ipleaders.in/z) with bare https://vakilsearch.com/foo."
        )
        out = sanitize_prose(text)
        assert "https://api.sci.gov.in/x.pdf" in out
        assert "google.com" not in out
        assert "ipleaders.in" not in out
        assert "vakilsearch.com" not in out

    def test_retrieved_sources_footer_stripped(self):
        # LLM echoes the input `## Retrieved Sources` marker back into the
        # response as a trailing footer. Must be stripped.
        text = (
            "A Power of Attorney is a legal instrument...\n\n"
            "The Supreme Court held X in Suraj Lamp.\n\n"
            "## Retrieved Sources\n\n"
            "1. **sci-44015** Suraj Lamp and Industries Private Limited "
            "vs. State of Haryana, (2012) 1 SCC 656\n"
        )
        out = sanitize_prose(text)
        assert "## Retrieved Sources" not in out
        assert "sci-44015" not in out
        # Body content survives.
        assert "Power of Attorney" in out
        assert "Suraj Lamp" in out

    def test_sources_and_citations_footer_stripped(self):
        text = (
            "The main analysis is here.\n\n"
            "### Sources & Citations\n\n"
            "1. sci-44015 Some case\n"
            "2. leg-ipc-302 Section 302 IPC\n"
        )
        out = sanitize_prose(text)
        assert "Sources & Citations" not in out
        assert "sci-44015" not in out
        assert "leg-ipc-302" not in out
        assert "The main analysis" in out

    def test_bold_sources_footer_stripped(self):
        # Bold-wrapped variant: **Sources:** ...
        text = (
            "Body of the response.\n\n"
            "**Sources:**\n"
            "- hc-bombay-12345 Some HC case\n"
        )
        out = sanitize_prose(text)
        assert "Sources:" not in out
        assert "hc-bombay-12345" not in out
        assert "Body of the response." in out

    def test_inline_internal_id_stripped(self):
        # An internal id can leak on its own line mid-response too.
        text = (
            "The court held X. Y was the issue.\n"
            "1. **sci-44015** Suraj Lamp v. State of Haryana\n"
            "Then Z happened.\n"
        )
        out = sanitize_prose(text)
        assert "sci-44015" not in out
        assert "The court held X." in out
        assert "Then Z happened." in out

    def test_no_footer_no_change(self):
        # A response with no footer / no internal ids passes through untouched
        # (apart from URL scrubbing which does nothing here).
        text = (
            "The Powers-of-Attorney Act, 1882 governs POAs in India. "
            "See also Section 17(1) of the Registration Act, 1908."
        )
        out = sanitize_prose(text)
        # No URLs in the input — nothing to strip. Whitespace collapsing only.
        assert "Powers-of-Attorney Act, 1882" in out
        assert "Registration Act, 1908" in out


# ---------------------------------------------------------------------------
# StreamingUrlFilter
# ---------------------------------------------------------------------------

class TestStreamingUrlFilter:
    def test_no_urls_passes_through(self):
        f = StreamingUrlFilter()
        assert f.push("hello ") == "hello "
        assert f.push("world") == "world"
        assert f.flush() == ""

    def test_url_split_across_two_tokens(self):
        # URL "https://evil.com/foo" arrives as "https://ev" + "il.com/foo "
        f = StreamingUrlFilter()
        # First chunk contains scheme + partial host — should HOLD from `https://`.
        out1 = f.push("prefix https://ev")
        assert out1 == "prefix "
        # Second chunk completes the URL with a trailing space terminator.
        out2 = f.push("il.com/foo suffix")
        assert "evil.com" not in out2
        assert "suffix" in out2

    def test_whitelisted_url_split_across_tokens_kept(self):
        f = StreamingUrlFilter()
        out1 = f.push("PDF: https://api.sci.gov.in/x")
        # Buffer holds from `https://` since no terminator arrived yet.
        assert "https://api.sci.gov.in" not in out1
        out2 = f.push("yz.pdf here")
        combined = out1 + out2
        assert "https://api.sci.gov.in/xyz.pdf" in combined
        assert "here" in combined

    def test_scheme_partial_at_end_of_chunk(self):
        # "htt" at end of a chunk — must be held, not emitted, in case the
        # next chunk completes it into a URL.
        f = StreamingUrlFilter()
        out1 = f.push("visit htt")
        assert out1 == "visit "
        out2 = f.push("ps://evil.com/x done")
        assert "evil.com" not in out2
        assert "done" in out2

    def test_flush_drains_held_partial(self):
        # If the stream closes with an unfinished URL in the buffer, flush()
        # must drain the tail through sanitize_prose.
        f = StreamingUrlFilter()
        f.push("check https://evil.com/foo")  # no terminator
        tail = f.flush()
        assert "evil.com" not in tail

    def test_url_immediately_at_chunk_start(self):
        f = StreamingUrlFilter()
        out = f.push("https://api.sci.gov.in/x.pdf yes")
        assert "https://api.sci.gov.in/x.pdf" in out
        assert "yes" in out

    def test_many_small_chunks(self):
        f = StreamingUrlFilter()
        assembled = ""
        for ch in "prefix https://evil.com/foo suffix":
            assembled += f.push(ch)
        assembled += f.flush()
        assert "evil.com" not in assembled
        assert "prefix" in assembled
        assert "suffix" in assembled

    def test_multiple_urls_in_single_chunk(self):
        f = StreamingUrlFilter()
        out = f.push("a https://evil.com/x b https://api.sci.gov.in/y.pdf c")
        assert "evil.com" not in out
        assert "https://api.sci.gov.in/y.pdf" in out
        assert "a " in out
        assert " b " in out
        assert " c" in out

    def test_empty_push_returns_empty(self):
        f = StreamingUrlFilter()
        assert f.push("") == ""
        assert f.flush() == ""
