"""Compliance Check — Scan legal drafts for issues before court filing.

Analyzes legal documents and flags:
- Missing mandatory clauses
- Procedural errors (wrong court, missing prayer, wrong format)
- Incorrect/outdated statutory references
- Missing signatures/verification sections
- Jurisdictional issues
- Limitation period concerns
- Stamp duty / registration requirements
- Format/structure deficiencies

Uses Gemini Flash for intelligent analysis with Indian legal domain expertise.
"""

from __future__ import annotations

import asyncio
from datetime import date

from core.clients import get_gemini_flash_full
from core.logger import get_logger, log_time

log = get_logger("Compliance")


COMPLIANCE_PROMPT = """You are an expert Indian legal compliance reviewer. Analyze the provided legal document and identify ALL compliance issues, missing elements, and potential problems.

## Document to Review:

{text}

## Document Type Context (if known): {doc_type}

## Review Checklist

Analyze the document against these criteria and report findings:

### A. STRUCTURAL COMPLIANCE
- Does the document have proper title/heading?
- Are all necessary sections present for this document type?
- Is the format appropriate for the intended court/authority?
- Are parties properly identified with full names, addresses, ages?
- Is there a proper prayer/relief clause (for petitions)?
- Is there a verification/affidavit section where required?

### B. STATUTORY COMPLIANCE
- Are all cited statutes correct and current?
- Are old laws referenced that should cite new equivalents (IPC→BNS, CrPC→BNSS, IEA→BSA)?
- Are section numbers accurate?
- Is the limitation period complied with?
- Are mandatory procedural requirements met (e.g., Section 80 CPC notice for government suits)?

### C. JURISDICTIONAL COMPLIANCE
- Is the correct court/forum mentioned?
- Is territorial jurisdiction properly established?
- Is pecuniary jurisdiction addressed?
- Is subject-matter jurisdiction appropriate?

### D. PROCEDURAL COMPLIANCE
- Are required court fees/stamp duty addressed?
- Is proper cause of action stated?
- Are necessary parties joined?
- Are dates and timelines consistent?
- Is service of notice properly addressed?

### E. SUBSTANTIVE COMPLIANCE
- Are all essential elements of the claim/defense covered?
- Are relief/prayers specific and legally tenable?
- Are facts sufficient to support each legal ground?
- Is evidence properly referenced?

### F. FORMATTING & EXECUTION
- Is the document court-filing ready?
- Are signature blocks present?
- Is the advocate's details section present?
- Is the index/list of documents present where required?

## Output Format

Return a structured compliance report in markdown:

# COMPLIANCE CHECK REPORT

**Document Type:** [identified type]
**Date of Review:** {date}
**Overall Status:** [PASS / NEEDS ATTENTION / CRITICAL ISSUES]

## Summary
[2-3 sentence overview of compliance status]

## Critical Issues (Must Fix Before Filing)
[List each critical issue with:]
- **Issue:** [description]
- **Location:** [which section/clause]
- **Fix:** [specific recommendation]

(If none: "No critical issues found.")

## Warnings (Should Fix)
[List each warning:]
- **Warning:** [description]
- **Recommendation:** [how to fix]

(If none: "No warnings.")

## Suggestions (Optional Improvements)
[List suggestions for improvement:]
- **Suggestion:** [description]

(If none: "No additional suggestions.")

## Missing Elements Checklist
| Element | Status | Notes |
|---------|--------|-------|
| [element name] | Present/Missing/Incomplete | [details] |

## Compliance Score
**Score: X/10**
[Brief justification]

---
*Compliance review generated by Lawttorney AI. This is an automated check — always have a qualified legal professional review before filing.*

## Rules:
1. Be thorough but practical — flag real issues, not theoretical ones
2. For Indian law, check both old and new criminal codes
3. If the document type is unclear, infer it from content and state assumptions
4. Prioritize: Critical > Warnings > Suggestions
5. Be specific about WHERE in the document each issue is and HOW to fix it
6. Do NOT fabricate issues — only flag genuine compliance concerns
"""


async def check_compliance(
    text: str,
    doc_type: str = "",
) -> str:
    """Run compliance check on a legal document.

    Args:
        text: Legal document text (markdown)
        doc_type: Optional document type hint (e.g., "petition", "agreement")

    Returns:
        Compliance report as markdown string
    """
    if not text or len(text.strip()) < 50:
        return "# COMPLIANCE CHECK REPORT\n\n**Error:** Document is too short for meaningful compliance analysis."

    doc_type_str = doc_type if doc_type else "Auto-detect from content"

    try:
        with log_time(log, "Compliance check"):
            llm = get_gemini_flash_full(temperature=0.1)
            response = await asyncio.to_thread(
                llm.invoke,
                COMPLIANCE_PROMPT.format(
                    text=text,
                    doc_type=doc_type_str,
                    date=str(date.today()),
                ),
            )

        report = response.content.strip()

        log.info("Compliance check complete",
                 doc_len=len(text),
                 report_len=len(report),
                 doc_type=doc_type_str)

        return report

    except Exception as e:
        log.error("Compliance check failed", error=str(e), exc_info=True)
        return (
            "# COMPLIANCE CHECK REPORT\n\n"
            f"**Error:** Compliance check failed: {e}\n\n"
            "Please try again or review the document manually."
        )
