"""Word/PDF export for Lawttorney AI responses.

Converts markdown AI responses into professionally formatted legal documents.
Supports:
- DOCX (via python-docx): proper headings, tables, lists, citations, footer
- PDF (via PyMuPDF fitz.Story): HTML/CSS rendering with Unicode/Indic script support

Usage:
    from core.export import export_document
    buf, filename, media_type = export_document(title, markdown_text, fmt="docx")
"""

from __future__ import annotations

import io
import re
from datetime import datetime

from core.logger import get_logger
from core.sanitize import sanitize_output

log = get_logger("Export")


# ---------------------------------------------------------------------------
# DOCX Generation
# ---------------------------------------------------------------------------

def _create_docx_styles(doc):
    """Configure professional legal document styles on a python-docx Document."""
    from docx.shared import Pt, Inches, Cm, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.style import WD_STYLE_TYPE

    # Page setup: A4, 1-inch margins
    for section in doc.sections:
        section.page_width = Cm(21.0)
        section.page_height = Cm(29.7)
        section.top_margin = Cm(2.54)
        section.bottom_margin = Cm(2.54)
        section.left_margin = Cm(2.54)
        section.right_margin = Cm(2.54)

    styles = doc.styles

    # Normal/body style
    normal = styles["Normal"]
    normal.font.name = "Times New Roman"
    normal.font.size = Pt(11)
    normal.paragraph_format.space_after = Pt(6)
    normal.paragraph_format.line_spacing = 1.15

    # Heading styles
    for level, size, bold in [(1, 16, True), (2, 13, True), (3, 11, True)]:
        style = styles[f"Heading {level}"]
        style.font.name = "Times New Roman"
        style.font.size = Pt(size)
        style.font.bold = bold
        style.font.color.rgb = RGBColor(0x1A, 0x1A, 0x1A)
        style.paragraph_format.space_before = Pt(12)
        style.paragraph_format.space_after = Pt(6)

    # Citation style (custom)
    if "LT Citation" not in [s.name for s in styles]:
        citation_style = styles.add_style("LT Citation", WD_STYLE_TYPE.PARAGRAPH)
        citation_style.font.name = "Times New Roman"
        citation_style.font.size = Pt(9)
        citation_style.font.italic = True
        citation_style.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
        citation_style.paragraph_format.left_indent = Cm(1.0)
        citation_style.paragraph_format.space_after = Pt(3)

    return doc


def _add_footer(doc, text: str = "Generated by Lawttorney - Indian Legal AI Assistant"):
    """Add footer text to all sections of the document."""
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    for section in doc.sections:
        footer = section.footer
        footer.is_linked_to_previous = False
        p = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(text)
        run.font.name = "Times New Roman"
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
        run.font.italic = True


def _md_to_docx(doc, md_text: str):
    """Convert markdown text to python-docx document elements.

    Handles: headings, bold, italic, bullet lists, ordered lists, tables,
    code blocks, horizontal rules, and inline formatting.

    Sanitizes malformed tables before processing.
    """
    from docx.shared import Pt, RGBColor, Cm
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn

    md_text = _sanitize_md_tables(md_text)
    lines = md_text.split("\n")
    i = 0
    in_table = False
    table_rows = []

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # Skip empty lines
        if not stripped:
            i += 1
            continue

        # Code block (```)
        if stripped.startswith("```"):
            i += 1
            code_lines = []
            while i < len(lines) and not lines[i].strip().startswith("```"):
                code_lines.append(lines[i])
                i += 1
            i += 1  # skip closing ```
            p = doc.add_paragraph()
            p.style = doc.styles["Normal"]
            run = p.add_run("\n".join(code_lines))
            run.font.name = "Courier New"
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)
            continue

        # Table row (|...|)
        if stripped.startswith("|") and stripped.endswith("|"):
            # Collect all table rows
            if not in_table:
                in_table = True
                table_rows = []
            # Skip separator rows (|---|---|)
            if re.match(r"^\|[\s\-:|]+\|$", stripped):
                i += 1
                continue
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            table_rows.append(cells)
            i += 1
            # Check if next line is still table
            if i >= len(lines) or not lines[i].strip().startswith("|"):
                # Flush table
                in_table = False
                if table_rows:
                    _add_table(doc, table_rows)
                table_rows = []
            continue

        # Heading (# ## ###)
        heading_match = re.match(r"^(#{1,3})\s+(.+)$", stripped)
        if heading_match:
            level = len(heading_match.group(1))
            text = heading_match.group(2).strip()
            p = doc.add_heading(text, level=level)
            i += 1
            continue

        # Horizontal rule (--- or ***)
        if re.match(r"^[-*_]{3,}$", stripped):
            # Add a thin line via paragraph border
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(6)
            p.paragraph_format.space_after = Pt(6)
            i += 1
            continue

        # Bullet list (- or * or +)
        if re.match(r"^[\-*+]\s+", stripped):
            text = re.sub(r"^[\-*+]\s+", "", stripped)
            p = doc.add_paragraph(style="List Bullet")
            _add_formatted_text(p, text)
            i += 1
            continue

        # Ordered list (1. 2. etc.). Legal drafts number paragraphs LITERALLY —
        # the verification clause refers to them by number ("the contents of
        # paragraphs 1 to 22 are true"), so the count must be stable and
        # continuous. Word's "List Number" style STRIPS the literal number and
        # auto-renumbers, which RESTARTS at every heading/interruption (e.g.
        # after "## Grounds for Bail") — corrupting the exact numbering the
        # drafter computed. Keep the literal "1. " as text in a hanging-indent
        # paragraph so the filed document matches the source verbatim. (The
        # HTML console has the same defect in its own renderMarkdown; this fix
        # is the one that matters for the filed .docx.)
        if re.match(r"^\d+\.\s+", stripped):
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Cm(0.8)
            p.paragraph_format.first_line_indent = Cm(-0.8)
            _add_formatted_text(p, stripped)   # keep the literal number
            i += 1
            continue

        # Regular paragraph
        p = doc.add_paragraph()
        _add_formatted_text(p, stripped)
        i += 1


def _add_formatted_text(paragraph, text: str):
    """Add text with inline markdown formatting (bold, italic, code, links)."""
    from docx.shared import Pt, RGBColor

    # Pattern to split by inline formatting
    # Matches: **bold**, *italic*, `code`, [text](url)
    pattern = r"(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`|\[[^\]]+\]\([^)]+\))"
    parts = re.split(pattern, text)

    for part in parts:
        if not part:
            continue
        # Bold
        if part.startswith("**") and part.endswith("**"):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        # Italic
        elif part.startswith("*") and part.endswith("*"):
            run = paragraph.add_run(part[1:-1])
            run.italic = True
        # Inline code
        elif part.startswith("`") and part.endswith("`"):
            run = paragraph.add_run(part[1:-1])
            run.font.name = "Courier New"
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(0x66, 0x33, 0x99)
        # Link [text](url)
        elif part.startswith("[") and "](" in part:
            match = re.match(r"\[([^\]]+)\]\(([^)]+)\)", part)
            if match:
                run = paragraph.add_run(match.group(1))
                run.font.color.rgb = RGBColor(0x14, 0x3C, 0x78)
                run.underline = True
            else:
                paragraph.add_run(part)
        else:
            paragraph.add_run(part)


def _add_table(doc, rows: list[list[str]]):
    """Add a formatted table to the document."""
    from docx.shared import Pt, RGBColor, Cm
    from docx.oxml.ns import qn

    if not rows:
        return

    n_cols = max(len(r) for r in rows)
    table = doc.add_table(rows=len(rows), cols=n_cols)
    table.style = "Table Grid"

    for r_idx, row_data in enumerate(rows):
        for c_idx, cell_text in enumerate(row_data):
            if c_idx < n_cols:
                cell = table.rows[r_idx].cells[c_idx]
                cell.text = cell_text
                # Bold header row
                if r_idx == 0:
                    for p in cell.paragraphs:
                        for run in p.runs:
                            run.bold = True
                            run.font.size = Pt(9)
                else:
                    for p in cell.paragraphs:
                        for run in p.runs:
                            run.font.size = Pt(9)


def generate_docx(
    title: str,
    md_text: str,
    sources: list[dict] | None = None,
    created_at: str | None = None,
) -> io.BytesIO:
    """Generate a professionally formatted DOCX from markdown text.

    Args:
        title: Document title (from user query or custom)
        md_text: Markdown-formatted AI response
        sources: Optional list of source metadata dicts
        created_at: Optional timestamp string

    Returns:
        BytesIO buffer containing the DOCX file
    """
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()
    _create_docx_styles(doc)

    # Title
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Date line
    date_str = created_at or datetime.now().strftime("%d %B %Y")
    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = date_para.add_run(f"Date: {date_str}")
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
    run.italic = True

    # Separator
    doc.add_paragraph("_" * 60)

    # Main content
    _md_to_docx(doc, md_text)

    # Sources/Citations section
    if sources:
        doc.add_heading("Sources & Citations", level=2)
        for idx, src in enumerate(sources, 1):
            src_title = src.get("title", "Unknown Source")
            src_type = src.get("source_type", "")
            agent = src.get("agent_name", "")
            web_url = src.get("web_url", "")

            citation_text = f"{idx}. {src_title}"
            if src_type:
                citation_text += f" [{src_type}]"
            if agent:
                citation_text += f" (via {agent})"
            if web_url:
                citation_text += f" - {web_url}"

            p = doc.add_paragraph(style="LT Citation")
            p.add_run(citation_text)

    # Footer
    _add_footer(doc)

    # Write to buffer
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)

    log.info("DOCX generated", title=title[:60], size_kb=buf.getbuffer().nbytes // 1024)
    return buf


# ---------------------------------------------------------------------------
# PDF Generation
# ---------------------------------------------------------------------------

def _sanitize_md_tables(md_text: str) -> str:
    """Fix malformed markdown tables that cause rendering issues.

    - Truncates excessively long separator rows (|:---|:---|...)
    - Removes consecutive dash-only lines (broken table overflow)
    - Limits repeated separator patterns to max 3 consecutive
    """
    lines = md_text.split("\n")
    cleaned = []
    consecutive_dashes = 0

    for i, line in enumerate(lines):
        stripped = line.strip()

        # Detect lines that are ONLY dashes, pipes, colons, spaces (table junk)
        is_dash_line = bool(stripped) and bool(re.match(r"^[-\s|:]+$", stripped)) and len(stripped) > 20

        if is_dash_line:
            consecutive_dashes += 1
            if consecutive_dashes <= 1:
                # Keep first dash line (could be a valid table separator or HR)
                # But truncate if too long
                if len(stripped) > 80:
                    cleaned.append("---")
                else:
                    cleaned.append(line)
            # Skip all subsequent consecutive dash lines
            continue

        # Reset counter on non-dash line
        consecutive_dashes = 0

        # Truncate excessively long table separator rows with pipes
        if re.match(r"^\|[\s\-:|]+\|$", stripped) and len(stripped) > 80:
            cols = stripped.strip("|").split("|")
            n_cols = min(len(cols), 10)
            short_sep = "| " + " | ".join(":---" for _ in range(n_cols)) + " |"
            cleaned.append(short_sep)
        else:
            cleaned.append(line)
    return "\n".join(cleaned)


def _md_to_html(md_text: str) -> str:
    """Convert markdown to HTML using markdown-it-py."""
    md_text = _sanitize_md_tables(md_text)
    try:
        from markdown_it import MarkdownIt
        md = MarkdownIt("commonmark", {"typographer": True})
        md.enable("table")
        return md.render(md_text)
    except ImportError:
        # Fallback: basic regex conversion
        log.warning("markdown-it-py not available, using basic HTML conversion")
        html = md_text
        # Headings
        html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
        html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
        html = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html, flags=re.MULTILINE)
        # Bold, italic
        html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
        html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)
        # Line breaks
        html = html.replace("\n\n", "</p><p>")
        html = f"<p>{html}</p>"
        return html


_PDF_CSS = """
@page {
    size: A4;
    margin: 2.5cm;
}
body {
    font-family: "Noto Serif", "Noto Sans Devanagari", "Times New Roman", serif;
    font-size: 11pt;
    line-height: 1.5;
    color: #1a1a1a;
}
h1 {
    font-size: 18pt;
    font-weight: bold;
    color: #14283c;
    text-align: center;
    margin-bottom: 6pt;
    border-bottom: 1px solid #cccccc;
    padding-bottom: 8pt;
}
h2 {
    font-size: 14pt;
    font-weight: bold;
    color: #1a3c78;
    margin-top: 14pt;
    margin-bottom: 6pt;
}
h3 {
    font-size: 12pt;
    font-weight: bold;
    color: #333333;
    margin-top: 10pt;
    margin-bottom: 4pt;
}
p {
    margin-bottom: 6pt;
    text-align: justify;
}
table {
    width: 100%;
    border-collapse: collapse;
    margin: 8pt 0;
    font-size: 9pt;
}
th, td {
    border: 1px solid #999999;
    padding: 4pt 6pt;
    text-align: left;
}
th {
    background-color: #f0f0f0;
    font-weight: bold;
}
ul, ol {
    margin-left: 20pt;
    margin-bottom: 6pt;
}
li {
    margin-bottom: 3pt;
}
code {
    font-family: "Courier New", monospace;
    font-size: 9pt;
    background-color: #f5f5f5;
    padding: 1pt 3pt;
}
pre {
    font-family: "Courier New", monospace;
    font-size: 9pt;
    background-color: #f5f5f5;
    padding: 8pt;
    border: 1px solid #dddddd;
    margin: 6pt 0;
}
.meta {
    text-align: center;
    color: #666666;
    font-size: 10pt;
    font-style: italic;
    margin-bottom: 12pt;
}
.footer {
    text-align: center;
    color: #999999;
    font-size: 8pt;
    font-style: italic;
    margin-top: 20pt;
    border-top: 1px solid #cccccc;
    padding-top: 6pt;
}
.citation {
    font-size: 9pt;
    color: #555555;
    font-style: italic;
    margin-left: 1cm;
    margin-bottom: 3pt;
}
"""


def generate_pdf(
    title: str,
    md_text: str,
    sources: list[dict] | None = None,
    created_at: str | None = None,
) -> io.BytesIO:
    """Generate a professionally formatted PDF from markdown text.

    Uses PyMuPDF's Story API for HTML/CSS rendering with full Unicode support.

    Args:
        title: Document title
        md_text: Markdown-formatted AI response
        sources: Optional list of source metadata dicts
        created_at: Optional timestamp string

    Returns:
        BytesIO buffer containing the PDF file
    """
    import fitz

    date_str = created_at or datetime.now().strftime("%d %B %Y")

    # Convert markdown to HTML
    body_html = _md_to_html(md_text)

    # Build citations HTML
    citations_html = ""
    if sources:
        citations_html = "<h2>Sources & Citations</h2>"
        for idx, src in enumerate(sources, 1):
            src_title = src.get("title", "Unknown Source")
            src_type = src.get("source_type", "")
            agent = src.get("agent_name", "")
            web_url = src.get("web_url", "")
            line = f"{idx}. {src_title}"
            if src_type:
                line += f" [{src_type}]"
            if agent:
                line += f" (via {agent})"
            if web_url:
                line += f" - {web_url}"
            citations_html += f'<p class="citation">{line}</p>'

    # Assemble full HTML document
    html = f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body>
    <h1>{_escape_html(title)}</h1>
    <p class="meta">Date: {date_str}</p>
    {body_html}
    {citations_html}
    <p class="footer">Generated by Lawttorney - Indian Legal AI Assistant</p>
</body>
</html>"""

    buf = io.BytesIO()

    try:
        # Use Story API: Story + DocumentWriter for multi-page PDF
        story = fitz.Story(html=html, user_css=_PDF_CSS)
        page_rect = fitz.Rect(0, 0, 595.28, 841.89)
        content_rect = fitz.Rect(72, 72, 595.28 - 72, 841.89 - 72)

        writer = fitz.DocumentWriter(buf)

        def rectfn(rect_num, filled):
            """Called by Story.write() to get the rectangle for each content area."""
            return content_rect, page_rect, None  # content_rect, mediabox, None

        story.write(writer, rectfn)
        writer.close()
        buf.seek(0)
    except Exception as story_err:
        log.warning("PDF Story rendering failed, using text-based fallback",
                    error=str(story_err))
        buf = io.BytesIO()
        pdf_doc = fitz.open()
        _generate_pdf_simple(pdf_doc, title, md_text, date_str, sources)
        pdf_doc.save(buf)
        pdf_doc.close()

    buf.seek(0)
    log.info("PDF generated", title=title[:60], size_kb=buf.getbuffer().nbytes // 1024)
    return buf


def _generate_pdf_simple(
    doc,
    title: str,
    md_text: str,
    date_str: str,
    sources: list[dict] | None = None,
):
    """Simple text-based PDF fallback when Story API is unavailable."""
    import fitz

    # Strip markdown formatting for plain text
    text = md_text
    text = re.sub(r"#{1,3}\s+", "", text)  # Remove heading markers
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)  # Remove bold
    text = re.sub(r"\*(.+?)\*", r"\1", text)  # Remove italic
    text = re.sub(r"`(.+?)`", r"\1", text)  # Remove code
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)  # Remove links

    full_text = f"{title}\n\nDate: {date_str}\n\n{'='*60}\n\n{text}"

    if sources:
        full_text += "\n\nSources & Citations\n" + "-" * 40 + "\n"
        for idx, src in enumerate(sources, 1):
            full_text += f"{idx}. {src.get('title', 'Unknown')}\n"

    full_text += f"\n\n{'='*60}\nGenerated by Lawttorney - Indian Legal AI Assistant"

    # Insert text page by page
    fontsize = 11
    margin = 72
    page_rect = fitz.Rect(0, 0, 595.28, 841.89)
    text_rect = fitz.Rect(margin, margin, 595.28 - margin, 841.89 - margin)

    remaining = full_text
    while remaining:
        page = doc.new_page(width=page_rect.width, height=page_rect.height)
        # insert_textbox returns remaining text that didn't fit
        rc = page.insert_textbox(
            text_rect,
            remaining,
            fontsize=fontsize,
            fontname="helv",
            align=fitz.TEXT_ALIGN_JUSTIFY,
        )
        if rc < 0:
            # Text overflowed — estimate how much fit and continue
            # Approximate chars per page
            chars_per_page = int(text_rect.width / (fontsize * 0.5) * text_rect.height / (fontsize * 1.3))
            remaining = remaining[chars_per_page:]
        else:
            remaining = ""


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def export_document(
    title: str,
    md_text: str,
    fmt: str = "docx",
    sources: list[dict] | None = None,
    created_at: str | None = None,
) -> tuple[io.BytesIO, str, str]:
    """Export an AI response as a downloadable document.

    Args:
        title: Document title
        md_text: Markdown-formatted AI response text
        fmt: "docx" or "pdf"
        sources: Optional list of source metadata dicts
        created_at: Optional timestamp string

    Returns:
        Tuple of (BytesIO buffer, filename, media_type)
    """
    # Sanitize LLM output before any rendering
    md_text = sanitize_output(md_text)

    # Sanitize title for filename
    safe_title = re.sub(r"[^\w\s-]", "", title[:50]).strip().replace(" ", "_")
    if not safe_title:
        safe_title = "lawttorney_export"
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")

    if fmt == "pdf":
        buf = generate_pdf(title, md_text, sources, created_at)
        filename = f"{safe_title}_{timestamp}.pdf"
        media_type = "application/pdf"
    else:
        buf = generate_docx(title, md_text, sources, created_at)
        filename = f"{safe_title}_{timestamp}.docx"
        media_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

    log.info("Export complete", format=fmt, filename=filename)
    return buf, filename, media_type