"""Research Memo Generator — Restructures AI responses into formal legal memoranda.

Takes the AI response markdown + query + sources and uses LLM to produce
a structured legal research memo with:
- Issue Presented
- Brief Answer
- Applicable Law
- Discussion & Analysis
- Sources & Citations
- Conclusion
- Disclaimer

Uses Gemini Flash for the restructuring (fast, cheap, large context).
"""

from __future__ import annotations

import asyncio
from datetime import date

from core.clients import get_gemini_flash_full
from core.logger import get_logger, log_time
from core.sanitize import sanitize_output

log = get_logger("Memo")


MEMO_PROMPT = """You are a senior legal research assistant at an Indian law firm. Your task is to restructure the provided AI-generated legal response into a formal **Legal Research Memorandum**.

## Input
- **Client Query:** {query}
- **AI Research Response:** (provided below)
- **Sources Used:** {sources_text}
- **Agents Used:** {agents_text}
- **Date:** {date}

## Output Format
Generate a professional legal research memorandum in markdown with EXACTLY these sections:

# LEGAL RESEARCH MEMORANDUM

**Date:** {date}
**Re:** [derive a concise subject line from the query]
**Prepared by:** Lawttorney AI Legal Research Assistant

---

## I. ISSUE PRESENTED

[Reframe the user's query as a formal legal issue/question. Use standard legal memo language like "Whether..." or "What are the legal implications of..."]

## II. BRIEF ANSWER

[Provide a 2-4 sentence executive summary answering the issue. State the conclusion upfront with the key legal basis.]

## III. APPLICABLE LAW

[List the relevant statutes, acts, sections, and constitutional provisions that govern this issue. Use proper citation format for Indian law.]

## IV. DISCUSSION & ANALYSIS

[This is the main body. Restructure the AI response into a logical legal analysis:
- Organize by legal argument, not by source
- Cite specific sections, case laws, and provisions
- Include relevant Supreme Court and High Court precedents if mentioned
- Analyze applicability to the client's situation
- Discuss any conflicting interpretations or evolving jurisprudence]

## V. RELEVANT CASE LAW

[List key cases cited in the response with:
- Case name and citation
- Court and date
- Key holding/ratio
- Relevance to the issue]

(If no specific cases were cited, write: "No specific case citations were identified in the research. Further case law research is recommended.")

## VI. SOURCES & REFERENCES

[List all sources from the metadata, including:
- Database sources (Elasticsearch indices searched)
- Web sources (if web fallback was used)
- Acts and sections referenced]

## VII. CONCLUSION & RECOMMENDATION

[Provide a clear conclusion with actionable recommendations. State any caveats or areas requiring further research.]

## VIII. DISCLAIMER

This memorandum is generated by Lawttorney AI Legal Research Assistant for informational and research purposes only. It does not constitute legal advice. The accuracy of AI-generated content should be independently verified. Consult a qualified legal professional before taking any action based on this research.

---

## Rules
1. Write in formal legal English, even if the original query was in another language
2. Maintain all citations, case names, section numbers exactly as they appear in the source
3. Do NOT fabricate any case law, citations, or legal provisions not present in the AI response
4. If the AI response contains information in Hindi/Marathi/other Indian languages, translate the key points to English in the memo but preserve original statutory terms
5. The memo should be comprehensive but concise — aim for a document a senior partner would review
6. Use Indian legal citation format throughout

## AI Research Response to Restructure:

{response_text}
"""


async def generate_memo(
    query: str,
    response_text: str,
    sources: list[dict] | None = None,
    agents_used: list[str] | None = None,
) -> str:
    """Generate a structured legal research memorandum from an AI response.

    Args:
        query: The original user query
        response_text: The AI-generated response (markdown)
        sources: Source metadata from the response
        agents_used: List of agents that contributed

    Returns:
        Formatted research memo as markdown string
    """
    # Build sources text
    sources_text = "None provided"
    if sources:
        source_lines = []
        for i, src in enumerate(sources, 1):
            parts = [src.get("title", "Unknown")]
            if src.get("source_type"):
                parts.append(f"[{src['source_type']}]")
            if src.get("agent_name"):
                parts.append(f"(via {src['agent_name']})")
            if src.get("court_name"):
                parts.append(f"Court: {src['court_name']}")
            if src.get("case_no"):
                parts.append(f"Case: {src['case_no']}")
            if src.get("judgment_date"):
                parts.append(f"Date: {src['judgment_date']}")
            if src.get("web_url"):
                parts.append(f"URL: {src['web_url']}")
            if src.get("doc_link"):
                parts.append(f"Doc: {src['doc_link']}")
            source_lines.append(f"{i}. {' | '.join(parts)}")
        sources_text = "\n".join(source_lines)

    agents_text = ", ".join(agents_used) if agents_used else "Not specified"

    try:
        with log_time(log, "Research memo generation"):
            llm = get_gemini_flash_full(temperature=0.2)
            response = await asyncio.to_thread(
                llm.invoke,
                MEMO_PROMPT.format(
                    query=query,
                    response_text=response_text,
                    sources_text=sources_text,
                    agents_text=agents_text,
                    date=str(date.today()),
                ),
            )

        memo_md = sanitize_output(response.text.strip())

        log.info("Research memo generated",
                 query=query[:80],
                 memo_len=len(memo_md),
                 sources_count=len(sources) if sources else 0)

        return memo_md

    except Exception as e:
        log.error("Memo generation failed, returning basic memo",
                  error=str(e), exc_info=True)
        # Fallback: basic formatting without LLM
        return _basic_memo_fallback(query, response_text, sources_text, agents_text)


def _basic_memo_fallback(
    query: str,
    response_text: str,
    sources_text: str,
    agents_text: str,
) -> str:
    """Generate a basic memo without LLM when the LLM call fails."""
    today = str(date.today())
    return f"""# LEGAL RESEARCH MEMORANDUM

**Date:** {today}
**Re:** {query[:100]}
**Prepared by:** Lawttorney AI Legal Research Assistant

---

## I. ISSUE PRESENTED

{query}

## II. BRIEF ANSWER

Please refer to the discussion section below for the detailed analysis.

## III. DISCUSSION & ANALYSIS

{response_text}

## IV. SOURCES & REFERENCES

{sources_text}

**Agents Used:** {agents_text}

## V. DISCLAIMER

This memorandum is generated by Lawttorney AI Legal Research Assistant for informational and research purposes only. It does not constitute legal advice. The accuracy of AI-generated content should be independently verified. Consult a qualified legal professional before taking any action based on this research.
"""