"""Table of Authorities Generator — Extracts and formats all legal citations.

Scans an AI response and produces a structured Table of Authorities with:
- Cases (case name, citation, court, date)
- Statutes (act name, section number)
- Constitutional Provisions (article number)
- Rules & Regulations

Uses Gemini Flash for intelligent citation extraction (understands Indian
legal citation formats, partial references, and inline mentions).
"""

from __future__ import annotations

import asyncio
from datetime import date

from core.clients import get_gemini_flash_full
from core.logger import get_logger, log_time
from core.sanitize import sanitize_output

log = get_logger("TOA")


TOA_PROMPT = """You are a legal citation specialist for Indian law. Extract ALL legal citations from the provided text and organize them into a Table of Authorities.

## Text to scan:

{response_text}

## Source metadata (if available):

{sources_text}

## Instructions

Extract EVERY legal reference mentioned in the text. Categorize them as follows:

Return a well-formatted markdown Table of Authorities with these sections:

# TABLE OF AUTHORITIES

**Date:** {date}
**Re:** {query}

---

## I. CASES CITED

[List every case mentioned. Format each as:]
[Number]. **[Full case name]** [citation if available]
   - Court: [court name]
   - Date/Year: [year or date]
   - Key Point: [one line on why this case was cited]

(If no cases found, write: "No cases cited in this document.")

## II. STATUTES & LEGISLATION

[List every act, section, rule mentioned. Format as:]
[Number]. **[Act Name]**, Section [number]
   - Subject: [brief description of what this section covers]

(If no statutes found, write: "No statutes cited in this document.")

## III. CONSTITUTIONAL PROVISIONS

[List every Article of the Constitution mentioned:]
[Number]. **Article [number]**, Constitution of India
   - Subject: [what this article covers]

(If no constitutional provisions found, write: "No constitutional provisions cited.")

## IV. RULES, REGULATIONS & NOTIFICATIONS

[List any rules, orders, notifications, circulars mentioned:]
[Number]. **[Rule/Order name]**
   - Issuing Authority: [authority]

(If none found, write: "No rules or regulations cited.")

## V. SECONDARY SOURCES

[List any textbooks, commentaries, legal journals mentioned:]
[Number]. **[Source name]**, [author if known]

(If none found, write: "No secondary sources cited.")

---

*Table of Authorities generated by Lawttorney AI*

## Rules:
1. Extract ONLY citations that actually appear in the text — do NOT fabricate any
2. Include partial references (e.g., "Section 302" without act name — infer IPC if context suggests)
3. Use standard Indian legal citation format
4. Preserve exact case names and citation numbers as they appear
5. If the same citation appears multiple times, list it once
6. For old/new law references (IPC/BNS, CrPC/BNSS), list both versions
"""


async def generate_toa(
    query: str,
    response_text: str,
    sources: list[dict] | None = None,
) -> str:
    """Generate a Table of Authorities from an AI response.

    Args:
        query: The original user query (for context)
        response_text: The AI-generated response (markdown)
        sources: Source metadata from the response

    Returns:
        Formatted Table of Authorities as markdown string
    """
    sources_text = "None provided"
    if sources:
        source_lines = []
        for i, src in enumerate(sources, 1):
            parts = [src.get("title", "Unknown")]
            if src.get("source_type"):
                parts.append(f"[{src['source_type']}]")
            if src.get("court_name"):
                parts.append(f"Court: {src['court_name']}")
            if src.get("case_no"):
                parts.append(f"Case: {src['case_no']}")
            if src.get("section_number"):
                parts.append(f"Section: {src['section_number']}")
            if src.get("act_name"):
                parts.append(f"Act: {src['act_name']}")
            source_lines.append(f"{i}. {' | '.join(parts)}")
        sources_text = "\n".join(source_lines)

    try:
        with log_time(log, "Table of Authorities generation"):
            llm = get_gemini_flash_full(temperature=0.1)
            response = await asyncio.to_thread(
                llm.invoke,
                TOA_PROMPT.format(
                    query=query[:200],
                    response_text=response_text,
                    sources_text=sources_text,
                    date=str(date.today()),
                ),
            )

        toa_md = sanitize_output(response.content.strip())
        log.info("TOA generated",
                 query=query[:80],
                 toa_len=len(toa_md),
                 sources_count=len(sources) if sources else 0)
        return toa_md

    except Exception as e:
        log.error("TOA generation failed, returning basic TOA",
                  error=str(e), exc_info=True)
        return _basic_toa_fallback(query, sources)


def _basic_toa_fallback(query: str, sources: list[dict] | None) -> str:
    """Basic TOA without LLM when LLM call fails."""
    today = str(date.today())
    lines = [
        f"# TABLE OF AUTHORITIES\n",
        f"**Date:** {today}",
        f"**Re:** {query[:100]}\n",
        "---\n",
        "## SOURCES\n",
    ]
    if sources:
        for i, src in enumerate(sources, 1):
            title = src.get("title", "Unknown Source")
            stype = src.get("source_type", "")
            lines.append(f"{i}. **{title}** [{stype}]")
    else:
        lines.append("No sources available. Run citation extraction manually.")

    lines.append("\n---\n*Table of Authorities generated by Lawttorney AI*")
    return "\n".join(lines)
