"""Inline Tool: Legal disclaimer injection.

Pure function — no I/O, runs in-process with zero latency.
Migrated from: v1 utils/guardrails.py (add_disclaimer_if_needed)
"""

LEGAL_DISCLAIMER = (
    "\n\n---\n**Disclaimer:** This response is generated by an AI assistant and is for "
    "informational purposes only. It does not constitute legal advice. Please consult "
    "a qualified legal professional for advice specific to your situation."
)

# All legal task types get the disclaimer (BUG-15: previously only 4 of the
# 11 task types got one, leading to inconsistent footers across answers from
# the same chat session). Only `Non_legal` is excluded — greetings, casual
# chat, and bot-identity questions don't need a legal-advice disclaimer.
DISCLAIMER_TASKS = {
    "Scenario", "Legal_Concepts", "Other", "Drafting",
    "Document", "Judgment", "Legislation", "Newacts",
    "Constitution", "Maxim", "SCI_Judgment", "GST_Judgment",
}

DISCLAIMER_INDICATORS = [
    "does not constitute legal advice",
    "not a substitute for legal advice",
    "consult a qualified legal professional",
    "for informational purposes only",
]


def add_disclaimer(content: str, task: str) -> str:
    """Add legal disclaimer for applicable task types. Skips if already present."""
    if task not in DISCLAIMER_TASKS:
        return content

    content_lower = content.lower()
    if any(ind in content_lower for ind in DISCLAIMER_INDICATORS):
        return content

    return content + LEGAL_DISCLAIMER
